 GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                  xxx           ",
   "                                                   xx      xx    xx!xx          ",
   "                                    o o      xx                  x!!!x          ",
   "                                                                 xx!xx          ",
   "                                   xxxxx                          xvx           ",
   "                                                                            xx  ",
   "  xx          o  o   o  o                 o o                                x  ",
   "  x                                                                          x  ",
   "  x          xxxxxx  xxxxx               xxxxx                             o x  ",
   "  x                                                                          x  ",
   "  x  @                                                                       x  ",
   "  xxxxxxxxxxx             xxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "            x             x                          x     x     x!!!x          ",
   "            x!!!!!!!!!!!!!x                          x!!!!!x     x!!!x          ",
   "            x!!!!!!!!!!!!!x                          x!!!!!x     xxxxx          ",
   "            xxxxxxxxxxxxxxx                          xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!x                        xxxxxxx                                    x!x  ",
   "                                      x!!x                     xxxx     xxxx                                 x!x  ",
   "                                      x!!xxxxxxxxxx           xx           xx                                x!x  ",
   "                                      xx!!!!!!!!!!xx         xx             xx                               x!x  ",
   "                                       xxxxxxxxxx!!x         x                                    o   o   o  x!x  ",
   "                                                xx!x         x     o   o                                    xx!x  ",
   "                                                 x!x         x                                xxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx         x     x   x                        !!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xx            v                        ",
   "                                                               xxxx!!!!!xxxx                                      ",
   "                                               x     x            xxxxxxx        xxx         xxx                  ",
   "                                               x     x                           x x         x x                  ",
   "                                               x     x                             x         x                    ",
   "                                               x     x                             xx        x                    ",
   "                                               xx    x                             x         x                    ",
   "                                               x     x      o  o     x   x         x         x                    ",
   "               xxxxxxx        xxx   xxx        x     x               x   x         x         x                    ",
   "              xx     xx         x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "             xx       xx        x o x          x    xx               x   x   x               x                    ",
   "     @       x         x        x   x          x     x               x   x   x               x                    ",
   "    xxx      x         x        x   x          x     x               x   xxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx o xx         x     x               x     o     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !                    xx     xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                                  ",
   "                                                                                             xxxxxxxx             ",
   "           o      o      o     o       o                                                             x            ",
   "                                                                                                     x            ",
   "         x   x   xxx   xxxx   xxxx   x   x                                                    !!!!!!!x            ",
   "         x   x  x   x  x   x  x   x  x   x                                                   !!!!!!!!x            ",
   "     xxx xxxxx  xxxxx  xxxx   xxxx    x x                                                   vxxxxxxxx             ",
   "         x   x  x   x  x      x        x                                                                          ",
   "   @     x   x  x   x  x      x        x             o       o       o      o      o     o                        ",
   "xxxxxxx                                                                                                           ",
   "                       x   x   xxx   x      x       xxx   x     x  xxxxx  xxxxx  xx    x                          ",
   "                       x   x  x   x  x      x      x   x  x     x  x      x      x x   x                          ",
   "                       xxxxx  xxxxx  x  o   x      x   x  x  x  x  xxxxx  xxxxx  x  x  x          o    o          ",
   "                       x   x  x   x  x      x      x   x  x  x  x  x      x      x   x x                          ",
   "                       x   x  x   x  xxxxx  xxxxx   xxx    xx xx   xxxxx  xxxxx  x    xx         xxxxxxxxxx       ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                  o o                                     |  |                             xxxx                   ",
   "                                                          o  o            o   x               x                   ",
   "               xxxxxx                                                         x               x                   ",
   "              xx    xx        xxx                       xxxxxxxxx     xx      x               x                   ",
   "     o       xx      xx         x    xxxxxx    x     xxx              x   o xxx               x                   ",
   "             x        x         x              x     x                x       x      =        x                   ",
   "    xxx      x        x         x              x    xx                xxx         xxxxxx      x                   ",
   "    x x      x        x        xx              x     x                x   o       x x         x                   ",
   "!!!!x x!!!!!!x         x!!!!!xxx     xx!!!!!!!!xx    x!!!!!!!!!!      x           x x         x                   ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!      xxxxxxxxxxxxx xx!!!!!!!xx                   ",
   "!!!!x x!!!!!!x         x!!!!!x          o     o     xx!!!!!!xx !                     xx!!!!!xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x   o                 xx!!!!!!xx  !                      xxxxxxx                     ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
   
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;